liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 360x230 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [360, 230], mode: outbound }